ＷＥＢ開発４－３作成
ma-miyagawa/miya-tutorial2 pull request #12
Opened 2022-08-18 12:27 UTC by ma-miyagawa

2022-08-18 12:29 UTC, ma-miyagawa commented
[@山川宏賢](https://esm-fdhq.slack.com/team/U032H7CQGE8) [@yanagi-m](https://github.com/yanagi-m) [@MitsukiTanaka](https://github.com/MitsukiTanaka)

ＷＥＢ開発４－３の対応を行いました。ＧＡＳでデバッグを行い登録／更新の確認を行いました。
レビューをお願いします。

2022-08-19 00:00 UTC, hyamakawa requested changes
@ma-miyagawa 確認しました。コメントしたのでご確認、ご対応よろしくお願いします。

2022-08-19 00:00 UTC, hyamakawa commented on webdev1_1/Code.js
> +function isExistCounterTable(connection) {
関数名や関数の切り方など、みやすいなと思いました。さすがです。

insertとupdateですが、実はここまでゴリゴリに実装しなくても切り分けがさくっとできるので、
よければそのやり方で再度実装してみてください。

https://dev.mysql.com/doc/refman/5.6/ja/insert-on-duplicate.html

2022-08-20 05:14 UTC, ma-miyagawa commented on webdev1_1/Code.js
> +function isExistCounterTable(connection) {
ご指摘通り、INSERT ... ON DUPLICATE KEY UPDATEで更新するように修正しました。
この場合、プライマリキーが必要になりますので、テーブルの定義にIdの項目を追加しました。
再度、ご確認をお願いします。

2022-08-21 23:48 UTC, hyamakawa requested changes
@ma-miyagawa 

 keyが必要でしたね、ご対応ありがとうございます。
だいぶスッキリしましたね。
1点コメントしたのでご確認・ご対応よろしくお願いいたします。

2022-08-21 23:48 UTC, hyamakawa commented on webdev1_1/Code.js
> +  execSql += 'counter = ? ';
足していく必要はないのかなと思いました。
1行に書くと見にくいというのが理由でしたら、バッククォートで囲ってもいいのかなと思いました。
こんな感じ⬇︎

``` javascript
const execSql = `
    INSERT INTO counter_table (id ,counter) values (?, ?)
    ON DUPLICATE KEY UPDATE
    counter = ?
  `;
```

2022-08-22 12:14 UTC, ma-miyagawa commented on webdev1_1/Code.js
> +  execSql += 'counter = ? ';
@hyamakawa 

指摘に対して対応しました。ご確認をお願いします。
バッククオートで記載する方法があったのですね。新たな発見です。

2022-08-22 23:56 UTC, hyamakawa approved these changes
@ma-miyagawa 新たな発見、よかったです！lgtm🧇

2022-08-23 12:20 UTC, ma-miyagawa commented
レビューありがとうございました。マージします。

2022-08-23 12:20 UTC, merged