WEB開発1-1 初版
ma-miyagawa/miya-tutorial2 pull request #4
Opened 2022-06-02 11:58 UTC by ma-miyagawa

[@hyamakawa](https://github.com/hyamakawa) [@MitsukiTanaka](https://github.com/MitsukiTanaka) [@yanagi-m](https://github.com/yanagi-m) 

WEB開発1-1  カウントアップできるようにする　　を作成しました。
レビューをお願いします。
何か足りないことがありましたらご指摘をお願いします。

2022-06-03 09:17 UTC, hyamakawa requested changes
@ma-miyagawa 

確認しました。コメントしたので対応お願いいたします。  
また、下記2つをお願いしたいです。

- 画面の見た目を新規作成したり、変更した場合は、スクショを貼って欲しいです
- GoogleAppsScriptファイルを共有ドライブの方に置いてもらいたいです（動作確認しやすいように）

2022-06-03 09:17 UTC, hyamakawa commented on webdev1_1/Code.js
> +  }
2, 3行目のインデントが右にずれてる？

2022-06-03 12:50 UTC, ma-miyagawa commented on webdev1_1/index.html
> +      let count_up_btn = document.getElementById("btn_count_up");
再代入しないのでconstに変更しました

2022-06-03 12:51 UTC, ma-miyagawa commented on webdev1_1/Code.js
> +  }
インデントのずれを修正しました。

2022-06-03 12:52 UTC, ma-miyagawa commented on webdev1_1/.claspignore
> +!appsscript.json
行末空白削除を行いました

2022-06-03 12:52 UTC, ma-miyagawa commented on webdev1_1/Code.js
> +
行末空白削除を行いました

2022-06-03 12:52 UTC, ma-miyagawa commented on webdev1_1/appsscript.json
> +}
行末空白削除を行いました

2022-06-06 02:51 UTC, hyamakawa commented
@ma-miyagawa 

ありがとうございます、確認しました、LGTMです。  
フォルダ名が気になったのですが、1-1、1-2...単位でフォルダは作って欲しくないです。
毎回ファイルが新規作成されると、差分がフルで出ちゃうので。
よろしくお願いしますっ！

2022-06-07 11:37 UTC, ma-miyagawa commented
[@MitsukiTanaka](https://github.com/MitsukiTanaka) [@yanagi-m](https://github.com/yanagi-m) 

柳原さん、田中さん
お忙しいと思いますが、レビューをよろしくお願いします。

2022-06-07 22:05 UTC, hyamakawa commented
@ma-miyagawa 

 `webdev1_1` からさらにブランチを切って課題を進めることは可能なので、もしよければそういう進め方をしていただいても構いません（実際のプロジェクトでもちょくちょく発生することではあるので）。さらに切ったブランチのマージ先を `webdev1_1` にすればちゃんと差分出ますし。

2022-06-13 10:08 UTC, yanagi-m commented
@ma-miyagawa すみません、遅くなりました。LGTM です！

2022-06-13 10:08 UTC, yanagi-m commented
@ma-miyagawa すみません、遅くなりました。LGTM です！

2022-06-13 12:22 UTC, ma-miyagawa commented
[@yanagi-m](https://github.com/yanagi-m) 

お忙しいところ、ありがとうございました。
マージを行います

2022-06-13 12:22 UTC, merged