WEB開発２－２対応分
ma-miyagawa/miya-tutorial2 pull request #8
Opened 2022-07-03 10:54 UTC by ma-miyagawa

2022-07-03 10:59 UTC, ma-miyagawa commented
[@山川宏賢](https://esm-fdhq.slack.com/team/U032H7CQGE8) [@yanagi-m](https://github.com/yanagi-m) [@MitsukiTanaka](https://github.com/MitsukiTanaka)

WEB開発２－２の対応を行いました。
レビューをお願いします。
※前回、保存ボタンのサイズがずれていたので、他のボタンと同じように見栄えに修正しました。

2022-07-03 10:59 UTC, ma-miyagawa commented
![image](https://user-images.githubusercontent.com/29744935/177036537-62d9511a-353e-48cb-b204-ca4aaeb22f0a.png)

2022-07-03 22:50 UTC, hyamakawa requested changes
@ma-miyagawa 

対応お疲れ様です！
確認しコメントしましたので、ご確認・ご対応よろしくお願いします。

2022-07-03 22:50 UTC, hyamakawa commented on webdev1_1/Code.js
> +  if (!isFinite(value)) {
`isFinite` こんなのあるんです、ほおお。

2022-07-03 22:50 UTC, hyamakawa commented on webdev1_1/Code.js
> +  const template = HtmlService.createTemplateFromFile('index');
template変数を使ってなさそうなので、この処理は不要でしょうか？

2022-07-03 22:50 UTC, hyamakawa commented on webdev1_1/Code.js
> +  template.disp_count_val = getInitSheetData();
ほおお、doGetでやる、こんなやり方も確かにありますね。

2022-07-03 22:50 UTC, hyamakawa commented on webdev1_1/index.html
> +      ).getInitSheetData();
doGetでやってるなら、ここでもう一度getInitSheetDataを呼び出す必要はなさそうな気がするのですが、この処理はどういった理由でやられてますか？

2022-07-03 22:50 UTC, hyamakawa commented on webdev1_1/index.html
> +      <div id="disp_count"><?= disp_count_val ?></div>
`disp_count ` と `disp_count_val ` で使い分けてる部分が、コードを追いかける若干難しかったです。

disp_countをやめて、一律disp_count_valで表示やカウントアップを制御することはできないんですかね？

そうすると見やすそうな気がしました。

2022-07-04 12:35 UTC, ma-miyagawa commented on webdev1_1/Code.js
> +  if (!isFinite(value)) {
数値かどうかの判定でググったら出てきました

2022-07-04 12:35 UTC, ma-miyagawa commented on webdev1_1/Code.js
> +  const template = HtmlService.createTemplateFromFile('index');
確かに不要です。削除しておきます。

2022-07-06 13:01 UTC, ma-miyagawa commented
指摘対応を行いましたので、再度ご確認をお願いします。

2022-07-06 23:47 UTC, hyamakawa commented
@ma-miyagawa LGTM 🙆‍♂️

2022-07-10 11:58 UTC, ma-miyagawa commented
レビューありがとうございました。
マージします

2022-07-10 11:58 UTC, merged