WEB開発３－１作成
ma-miyagawa/miya-tutorial2 pull request #9
Opened 2022-07-18 22:18 UTC by ma-miyagawa

[@山川宏賢](https://esm-fdhq.slack.com/team/U032H7CQGE8) [@yanagi-m](https://github.com/yanagi-m) [@MitsukiTanaka](https://github.com/MitsukiTanaka)

ＷＥＢ開発３－１の対応を行いました。
レビューをよろしくお願いします。

2022-07-19 11:14 UTC, hyamakawa requested changes
@ma-miyagawa 確認しました。コメントしたのでご確認・ご対応よろしくお願いします！

2022-07-19 11:14 UTC, hyamakawa commented on webdev1_1/index.html
> +      <div class="box" v-show="show">
へええ、すごい発想！

2022-07-19 11:14 UTC, hyamakawa commented on webdev1_1/index.html
> +        disp_count_val: ' ',
どうして初期値にスペースが入ってるんですか？空文字でもいいのかなと思ってしまったのですが。

2022-07-19 11:14 UTC, hyamakawa commented on webdev1_1/index.html
> +        <div id="disp_count" v-bind:text-content.prop="disp_count_val">0</div>
初めてみました、 `bind:text-content.prop` こういうのがあるんですね。

2022-07-19 11:14 UTC, hyamakawa commented on webdev1_1/index.html
> +      created: function() {
`xxx: function() {}` としている部分は、JavaScriptの特性上 `xxx () {}` と書き換えられます。

毎回functionって書くの面倒だと思うので、ご連携でした！

2022-07-21 12:44 UTC, ma-miyagawa commented on webdev1_1/index.html
> +        disp_count_val: ' ',
カウンターの表示している部分が初期表示できなかった時、空白1文字にしていて後で空文字にしようと思っていたら修正が漏れていました。空文字を初期値に変更しました。

2022-07-21 12:46 UTC, ma-miyagawa commented on webdev1_1/index.html
> +      created: function() {
Vue.jsのP61に記載されていました。修正して動作確認を行いました。

2022-07-21 12:47 UTC, ma-miyagawa commented
指摘内容を対応しましたので、再度ご確認をお願いします。

2022-07-22 02:29 UTC, hyamakawa commented
@ma-miyagawa LGTM 🙆‍♂️

2022-07-24 01:38 UTC, ma-miyagawa commented
レビューありがとうございました。
マージします。

2022-07-24 01:39 UTC, merged